### PR TITLE
chore(utils): decomission mock server from juno apps

### PR DESCRIPTION
**Pull request by barsukov**
# Summary
Part of decomision utils is to make dependency on app obsolete, after we move all other deps we can delete this library.

# Changes Made

- fetchDb and fetchProxy will be removed as deps from all apps
- all logic will be deleted from useMock sections

# Related Issues

- #446 
- #633
- #634

# Screenshots (if applicable)

# Testing Instructions

1. `npm i`
2. `npm run TASK`
3. turbo dev or turbo test in apps like doop, example and greenhoust

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

### CODE REVIEW

**Review by ArtieReus — COMMENTED** [review]
If we remove the mock integretion in `doop`, do we want also to remove th db.json??
https://github.com/cloudoperators/juno/blob/wowa-decomision-mock-server/apps/doop/src/db.json

**Comment by barsukov** [comment]
As I mentioned yesterday we could not remove the db.json cause they use inside of the tests files, so we would do that only when carbon is finished.

**Review by ArtieReus — APPROVED** [review]
Lgtm. For the leftover I have created new tasks:
- #633
- #634

Thank you very much!!

**Review by andypf — APPROVED** [review]
👍

**Pull request merged**
