### PR TITLE
chore(docs): add decisions folder and adr template for future decisions

### PR DESCRIPTION
**Pull request by edda**
# Summary

This PR proposes a template for our decision records so that our future decision records follow the same pattern. 

# Changes Made

- Created a new subfolder `decisions` within the `docs` folder
- Added a decision record template `000_decision_template.md`
- Renamed the exisiting decision records following the proposed naming scheme (starts with a number that is incremented for every new record)

### CODE REVIEW

**Review by ArtieReus — DISMISSED** [review]
lgtm

**Comment by andypf** [comment]
@edda can you remove the `_decision`prefix from files in docs/decisions?

**Review by andypf — CHANGES_REQUESTED** [review]
please add proposals to docs

**Review by ArtieReus — APPROVED** [review]
lgtm

**Review by andypf — APPROVED** [review]
👍

**Review by hgw77 — APPROVED** [review]

**Pull request merged**
