### PR TITLE
chore(ui): fix Grid stories after Typescript migration

### PR DESCRIPTION
**Pull request by guoda-puidokaite**
# Summary

After merging the `Grid`, `GridColumn` and `GridRow` migration [PR](https://github.com/cloudoperators/juno/pull/595), I found that Storybook had a few unintended styling changes (as below). This PR fixes these documentation changes.

**Issues Found**: Old Storybook on left, after migration on right:
Screenshot 2024-11-08 at 10 30 27
Screenshot 2024-11-08 at 10 30 51
Screenshot 2024-11-08 at 10 31 03
Screenshot 2024-11-08 at 10 31 41
Screenshot 2024-11-08 at 10 32 01

# Changes Made

Fixed Storybook, as was.

# Related Issues

- https://github.com/cloudoperators/juno/issues/229

# Screenshots (if applicable)

# Testing Instructions

- Check `Grid`, `GridColumn` and `GridRow` Storybook

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

### CODE REVIEW

**Review by barsukov — DISMISSED** [review]
it is a good from my side you can transfer it to a normal PR

**Review by andypf — DISMISSED** [review]
LGTM

**Review by andypf — APPROVED** [review]
Very nice!

**Comment by barsukov** [comment]
Please make a changeset

**Review by barsukov — APPROVED** [review]

**Pull request merged**
